--Alter some detail table
ALTER TABLE BookingDetail ADD (
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    createdBy VARCHAR2(128) DEFAULT USER NOT NULL,
    updatedAt TIMESTAMP,
    updatedBy VARCHAR2(128)
);

ALTER TABLE CostDetail ADD (
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    createdBy VARCHAR2(128) DEFAULT USER NOT NULL,
    updatedAt TIMESTAMP,
    updatedBy VARCHAR2(128)
);

ALTER TABLE PromotionDetail ADD (
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    createdBy VARCHAR2(128) DEFAULT USER NOT NULL,
    updatedAt TIMESTAMP,
    updatedBy VARCHAR2(128)
);

--Trigger for update updatedAt/By column
CREATE OR REPLACE TRIGGER TRG_EMPLOYEE_BU
BEFORE UPDATE ON EMPLOYEE
FOR EACH ROW
BEGIN
	:NEW.updatedAt := CURRENT_TIMESTAMP;
	:NEW.updatedBy := USER;
END;

CREATE OR REPLACE TRIGGER TRG_TOURPLAN_BU
BEFORE UPDATE ON TourPlan
FOR EACH ROW
BEGIN
  :NEW.updatedAt := CURRENT_TIMESTAMP;
  :NEW.updatedBy := USER;
END;


CREATE OR REPLACE TRIGGER TRG_TOURTYPE_BU
BEFORE UPDATE ON TourType
FOR EACH ROW
BEGIN
  :NEW.updatedAt := CURRENT_TIMESTAMP;
  :NEW.updatedBy := USER;
END;


CREATE OR REPLACE TRIGGER TRG_COUNTRY_BU
BEFORE UPDATE ON Country
FOR EACH ROW
BEGIN
  :NEW.updatedAt := CURRENT_TIMESTAMP;
  :NEW.updatedBy := USER;
END;


CREATE OR REPLACE TRIGGER TRG_ITEMCOST_BU
BEFORE UPDATE ON ItemCost
FOR EACH ROW
BEGIN
  :NEW.updatedAt := CURRENT_TIMESTAMP;
  :NEW.updatedBy := USER;
END;


CREATE OR REPLACE TRIGGER TRG_GUIDE_BU
BEFORE UPDATE ON Guide
FOR EACH ROW
BEGIN
  :NEW.updatedAt := CURRENT_TIMESTAMP;
  :NEW.updatedBy := USER;
END;


CREATE OR REPLACE TRIGGER TRG_TOUR_BU
BEFORE UPDATE ON Tour
FOR EACH ROW
BEGIN
  :NEW.updatedAt := CURRENT_TIMESTAMP;
  :NEW.updatedBy := USER;
END;


CREATE OR REPLACE TRIGGER TRG_TOURDETAIL_BU
BEFORE UPDATE ON TourDetail
FOR EACH ROW
BEGIN
  :NEW.updatedAt := CURRENT_TIMESTAMP;
  :NEW.updatedBy := USER;
END;


CREATE OR REPLACE TRIGGER TRG_CUSTOMERTYPE_BU
BEFORE UPDATE ON CustomerType
FOR EACH ROW
BEGIN
  :NEW.updatedAt := CURRENT_TIMESTAMP;
  :NEW.updatedBy := USER;
END;


CREATE OR REPLACE TRIGGER TRG_CUSTOMER_BU
BEFORE UPDATE ON Customer
FOR EACH ROW
BEGIN
  :NEW.updatedAt := CURRENT_TIMESTAMP;
  :NEW.updatedBy := USER;
END;


CREATE OR REPLACE TRIGGER TRG_COSTTYPE_BU
BEFORE UPDATE ON CostType
FOR EACH ROW
BEGIN
  :NEW.updatedAt := CURRENT_TIMESTAMP;
  :NEW.updatedBy := USER;
END;


CREATE OR REPLACE TRIGGER TRG_PROMOTION_BU
BEFORE UPDATE ON Promotion
FOR EACH ROW
BEGIN
  :NEW.updatedAt := CURRENT_TIMESTAMP;
  :NEW.updatedBy := USER;
END;

CREATE OR REPLACE TRIGGER TRG_PROMOTIONDETAIL_BU
BEFORE UPDATE ON PromotionDetail
FOR EACH ROW
BEGIN
  :NEW.updatedAt := CURRENT_TIMESTAMP;
  :NEW.updatedBy := USER;
END;

CREATE OR REPLACE TRIGGER TRG_BOOKING_BU
BEFORE UPDATE ON Booking
FOR EACH ROW
BEGIN
  :NEW.updatedAt := CURRENT_TIMESTAMP;
  :NEW.updatedBy := USER;
END;

CREATE OR REPLACE TRIGGER TRG_BOOKINGDETAIL_BU
BEFORE UPDATE ON BookingDetail
FOR EACH ROW
BEGIN
  :NEW.updatedAt := CURRENT_TIMESTAMP;
  :NEW.updatedBy := USER;
END;

CREATE OR REPLACE TRIGGER TRG_COSTDETAIL_BU
BEFORE UPDATE ON CostDetail
FOR EACH ROW
BEGIN
  :NEW.updatedAt := CURRENT_TIMESTAMP;
  :NEW.updatedBy := USER;
END;

CREATE OR REPLACE TRIGGER TRG_DEPARTMENT_BU
BEFORE UPDATE ON Department
FOR EACH ROW
BEGIN
  :NEW.updatedAt := CURRENT_TIMESTAMP;
  :NEW.updatedBy := USER;
END;